Play.create(title:'Into the Woods', description:'fairy tale on crack', schedule:'now until forever', price:50.00)
Play.create(title:'Miss Saigon', description:'Vietnam War drama', schedule:'next 3 months', price:60.00)
Play.create(title:'Dr. Jekyll and Mr. Hyde', description:'Scientist gone mad', schedule:'next year', price:70.00)
Play.create(title:'Phantom of the Opera', description:'French opera drama', schedule:'next half a year', price:40.00)
Play.create(title:'The Lion King', description:'Disney fun stuff', schedule:'next 5 years', price:80.00)
